[alembic]
script_location = %(here)s/migrations
version_locations = %(here)s/migrations/versions/core
version_table = alembic_version
version_table_schema = platform_core
migration_target = core
prepend_sys_path = %(here)s/src
path_separator = os
sqlalchemy.url = postgresql+psycopg://ai_hub_platform_migrator:local-only-platform-migrator-password@localhost:5433/platform_db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
